NAME = libftgnl.a
CC = cc
CFLAGS = -Wall -Wextra -Werror
RM = rm -rf
AR = ar -rcs
SRCS = get_next_line.c get_next_line_utils.c
OBJS = $(SRCS:.c=.o)

all :
	@make $(NAME)

clean :
	@$(RM) $(OBJS)

fclean : clean
	@$(RM) $(NAME)

re :
	@make fclean
	@make all

$(NAME) : $(OBJS)
	@$(AR) $@ $^

%.o : %.c
	@$(CC) $(CFLAGS) -o $@ -c $<

.PHONY : all clean fclean re bonus
